import React from "react"

const AboutPage = (props) =>{
    return(
        <div className="AboutPageDiv">
            <div className="AboutPage__writtenSection">
                <div className="AboutPage__Header">
                    <h2>TL;DR</h2>
                    <p className="AboutPage__Content">
                        Podly is a platform that makes use of cutting edge Natural Language Processing to allow Podcasters to easily and accurately have their episodes transcribed. Once approved, these transcripts are then posted and can be easily accessed by the world.
                    </p>
                </div>
            </div>
            <div className="AboutPage__writtenSection">
                <div className="AboutPage__Header">
                    <h2>Purpose of This Project</h2>
                    <p className="AboutPage__Content">
                        This project provides for the needs of three distinct groups: <br />
                        <br />
                        1) For <b>Podcasters</b>, this platform provides a place to have their podcast episodes inexpensively transcribed. The expense is reduced without loss in transcript quality by making use of Natual Language Processing to substaintally decrease the time required to transcribe each podcast episode. <br />
                        <br />
                        2) For <b>Transcriptionists</b>, this platform provides a place to find work and an intuitive set of tools that makes their job easier and faster than ever. <br />
                        <br />
                        3) For <b>Researchers</b> (i.e. those who may be accessing the information within podcasts not just for entertainment), this platform provides a place to find complete podcast episode transcripts, allowing for easy skimming to find relevant information, and a way to create and save timestamped notes for later reference.
                    </p>
                </div>
            </div>
            <div className="AboutPage__writtenSection">
                <div className="AboutPage__Header">
                    <h2>Method</h2>
                    <p className="AboutPage__Content">
                        Podcasts are added by the owner adding a link to the RSS feed. From here, the Podcaster is able to see all available episodes and request for any untranscribed episodes to be transcribed. Once this request is put in, a copy of the episode is downloaded and stored in an AWS S3 bucket. The audio is then run through their transcription service, generating a base transcript with timestamps for each word. Once AWS has finished processing the episode, the base transcript is downloaded, parsed, and converted into a format suitable to be later edited.<br />
                        <br />
                        After the conversion process, the Transcription job is then made open for access to any Transcriptionist. AWS's transcription service, while one of the best Natural Language Processing services on the market, still makes a host of errors that the Transcriptionist then corrects. This is made effecient by using the timestamps originally generated by AWS: the in-browser editor tracks each word as the Transcriptionist is playing back the audio, allowing them to easily make corrections as they go. <br />
                        <br />
                        Once the Transcriptionist has finished, the transcript is made viewable exclusively to the Podcaster who originally requested the Transcript, allowing him/her to approve the transcript (which is then published), reject the transcript (which reopens the job for transcriptionists), or make any final edits. <br />
                        <br />
                        Once published, the Transcript can be accessed by any user. If the user is logged in s/he is able to leave timestamped notes visable only to that user.
                    </p>
                </div>
            </div>
            <div className="AboutPage__writtenSection">
                <div className="AboutPage__Header" id="editorHelp">
                    <h2>How To Use The Editor</h2>
                    <p className="AboutPage__Content">
                        While editing a podcast, one should start by pressing the play button on the player at the top of the screen. Track along with the podcast and look for any mistakes. When you see one, press the "enter" key, which will pause the podcast and allow you to use the arrow keys to highlight the exact word that is in error. Once that word is highlighted, simply type the correct word. If there are multiple errors in the same area, feel free to continue to use the arrow keys to navigate and clear any other errors. When you are ready to resume, press the "enter" key again. <br />
                        <br />
                        The transcriber is also responsible for correctly assigning names to each speaker. When you click on a speaker name (e.g. "speaker 1"), a list of options will come up allowing you to assign a name. These options let you either assign all text currently labeled as "speaker 1" to a given name, or only the text block you have clicked on. 
                        <br />
                        <br />
                        <div className="AboutPage__FirstImageSection" style ={ { backgroundImage: "url('/changeSpeaker.gif')" } }>

                        </div>
                         <br />
                        Likewise, if AWS does not correctly identify when there is a speaker change, you can highlight a section of text, triggering a menu to pop up allowing just that text to be reassigned. Do no worry if this creates two consecutive blocks by the same speaker as this will be corrected in post processing.
                        <br />
                        <br />
                        <div className="AboutPage__FirstImageSection" style ={ { backgroundImage: "url('/changeSection.gif')" } }>

                        </div>
                        <br />
                    </p>
                </div>
            </div>
            <div className="AboutPage__writtenSection">
                <div className="AboutPage__Header">
                    <h2>Restrictions</h2>
                    <p className="AboutPage__Content">
                        As the AWS Natual Language Processing service changes for every piece of audio analysed, the ability to request new episode transcripts is gated behind a special passcode. Please contact the creater, Brandon Bartlett, if you would like access to this functionality. I can be reached at brandonacb@gmail.com.
                    </p>
                </div>
            </div>
            
        </div>
    )
}

export default AboutPage